# Generated by Django 2.2.2 on 2019-06-25 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('abrev', models.CharField(max_length=5, verbose_name='abbreviation')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='barcode')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='quantity')),
                ('is_pack', models.BooleanField(default=False, verbose_name='is pack')),
                ('pack_quantity', models.CharField(blank=True, max_length=200, null=True, verbose_name='pack quantity')),
                ('lp_id', models.IntegerField(blank=True, null=True, verbose_name='los precios id')),
                ('lp_url', models.URLField(blank=True, null=True, verbose_name='los precios URL')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Brand', verbose_name='brand')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Measure', verbose_name='measure')),
                ('pack_unit_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Item', verbose_name='pack unit barcode')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
