# Generated by Django 2.2.2 on 2019-09-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lp_brand',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='los precios brand'),
        ),
        migrations.AddField(
            model_name='item',
            name='lp_complement',
            field=models.TextField(blank=True, null=True, verbose_name='los precios complement'),
        ),
        migrations.AddField(
            model_name='item',
            name='lp_product',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='los precios product'),
        ),
        migrations.AddField(
            model_name='item',
            name='lp_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='los precios size'),
        ),
        migrations.AddField(
            model_name='item',
            name='lp_store_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='los precios store id'),
        ),
    ]
