# Generated by Django 2.2.2 on 2019-09-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190921_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lp_store_url',
            field=models.URLField(blank=True, null=True, verbose_name='los precios store URL'),
        ),
    ]
